name: my_gas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.4.0
  grouped_buttons: ^1.0.4
  loading: ^1.0.2
  mime: ^0.9.6+3
  progress_dialog: ^1.2.0
  webview_flutter: ^0.3.0
  time_ago_provider: ^1.0.3
  location: ^2.3.5
  fluttertoast: ^3.1.3
  pin_code_text_field: ^1.5.0
  image_picker: ^0.6.2+1
  intl: ^0.16.0
  flutter_rating_bar: ^3.0.0+1
  firebase_core: ^0.4.0
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.0+1
  firebase_database:
  google_sign_in: ^4.0.1+1
  rxdart: ^0.20.0
  flutter_facebook_login: ^2.0.0
  scoped_model: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"


flutter_icons:
  image_path: "assets/images/app_icon_ios.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - assets/images/app_icon/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
